module.exports = {
  aliases: {
    "#styles": "src/styles",
    "#animations": "src/animations",
    "#common": "src/components/common",
    "#components": "src/components",
    "#layouts": "src/layouts",
    "#img": "src/assets/img",
    "#assets": "src/assets",
    "#queries": "src/queries",
    "#queryTypes": "src/queries/graphql",
    ".": "typings",
  },
  extensions: [
    ".js",
    ".jsx",
    ".react.js",
    ".react.jsx",
    ".ts",
    ".d.ts",
    ".d.tsx",
    ".tsx",
    ".react.ts",
    ".react.tsx",
  ],
};
